### ISSUE TITLE
[TODO] MAIN

### ISSUE THREAD

**Issue by CheHyeonYeong** [CheHyeonYeong/LooPRPG#10]
## 작업 상세 내용

- [x] 맵 이동
- [x] 게임 루프 설정
- [x] 게임 루프 설정
- [x] 전투 로직
- [x] 승패처리
- [x] 이벤트 및 보상 처리
- [x] 게임 종료 및 재시작 로직
