### ISSUE TITLE
[TODO] EVENT

### ISSUE THREAD

**Issue by CheHyeonYeong** [CheHyeonYeong/LooPRPG#11]
## 작업 상세 내용

- [x] 최상위 이벤트 
- [x] 전투 이벤트 발생
- [x] 회복 이벤트 발생
- [x] 보상 Box
- [x] 회복 보상
- [x] 공격력 2배 보상
- [x] 귀여운 이모지 보상
- [x] 싸움 결과 반환
- [x] monsterGrow

**Comment by CheHyeonYeong** [comment]
> ## 작업 상세 내용
> * [ ]  최상위 이벤트
> * [ ]  전투 이벤트 발생
> * [ ]  회복 이벤트 발생
> * [ ]  보상 Box
> * [ ]  회복 보상
> * [ ]  공격력 2배 보상
> * [ ]  귀여운 이모지 보상
> * [ ]  싸움 결과 반환
> * [ ]  monsterGrow
> 
> ## 참고할만한 자료(선택)
